### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by mdozmorov** [lindsayhrlee/SnapHiC-D#1]
We are trying to run SnapHiC-D on our scHi-C data. It has 1M resolution 1M. Your examples, including the "*filter_regions.txt" files, are at 10kb resolution. I cannot find documentation how to create the "filter_regions" file. When running our data with your "filter_regions" file, SnapHiC-D breaks with the following error:
<details>
  <summary>Full error output</summary>
Traceback (most recent call last):
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/bin/SnapHiC-D", line 8, in <module>
    sys.exit(main())
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/run_SnapHiC_D.py", line 29, in diff_loops
    bid_path=bidpath, gid_path=gidpath
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/SnapHiC_D/SnapHiC_D.py", line 93, in call_diff_loops
    for gap in gaps if os.path.exists(result_fpath.format(gap))
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/Users/gfc2/miniconda3/envs/SnapHiC_D_env/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
</details>

To reproduce, resolution of the example files in `sox2_ESC` and `sox2_NPC` can be modified like this:
```{bash}
for file in *.bedpe; do 
  echo `basename $file`;  
  awk '{OFS="\t"; $2=$2*100; $3=$3*100; $5=$5*100; $6=$6*100; print}' $file > tmp.bed; 
  mv tmp.bed $file; 
done
```
And then SnapHiC-D stops working. Please, advice, how to solve this?
```{bash}
SnapHiC-D diff-loops -i sox2_ESC -j sox2_NPC -o output -c chr3 -n 2 \
                     -b "ext/mm10_filter_regions.txt" \
                     -g "ext/mm10.refGene.transcript.TSS.061421.txt"
```

**Comment by lindsayhrlee** [comment]
Hi, thanks for your interest in SnapHiC-D.

We created the filter region files based on the ENCODE blacklist regions, similar to what we did in SnapHiC which you should be using to generate the input data for SnapHiC-D.

For SnapHiC-D, our goal is to detect differential TSS-centered enhancer-promoter interactions, and we only test SnapHiC-D on 10Kb bin resolution scHi-C data. We haven't analyzed 1Mb bin resolution scHi-C data yet. SnapHiC-D may not be appropriate for 1Mb bin resolution as of now.
